{% set name = "mattersim" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mattersim-{{ version }}.tar.gz
  sha256: 54a62343525c8a69ee953e765bab9b8733d6192f4dbfeca9f44cd5742c195304

build:
  skip: true  # [py<39 or not linux]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - cython >=0.29.32
    - numpy <2
    - pip
    - python
    - setuptools >=45
    - setuptools-scm
    - wheel
  run:
    - ase >=3.23.0
    - azure-storage-blob
    - azure-identity
    - deprecated
    - e3nn ==0.5.0
    - emmet-core <0.84
    - loguru
    - mp-api
    - {{ pin_compatible('numpy') }}
    - opt_einsum_fx
    - pydantic ==2.9.2
    - pymatgen
    - python
    - pytorch =>2.2.0
    - pytorch_geometric ==2.5.3
    - seekpath
    - torchvision =>0.17.0
    - torchaudio =>2.2.0
    - torch-runstats ==0.2.0
    - torchmetrics >=0.10.0
    - torch-ema ==0.3

test:
  imports:
    - mattersim
    - mattersim.datasets
    - mattersim.forcefield

about:
  home: https://microsoft.github.io/mattersim
  dev_url: https://github.com/microsoft/mattersim
  summary: 'MatterSim: A Deep Learning Atomistic Model Across Elements, Temperatures and Pressures.'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
